### ISSUE TITLE
apollo-server-express doesn't have graphiqlExpress, graphqlExpress

### ISSUE THREAD

**Issue by ghost** [klendi/mern-apollo-graphql-boilerplate#2]
Hi just so you know, updating dependencies to Apollo Server 2 means your code won't work any more. For more information check out this migration guide

https://www.apollographql.com/docs/apollo-server/v2/migration-two-dot.html

**Comment by klendi** [comment]
Hello, thanks for opening this issue. Thanks for informing me, I successfully migrated to Apollo Server 2 and  connected it with the backend (a5c4f19 ) . Everything works perfectly now. :smiley:
